include:
  - board: nice_nano_v2
    shield: cosmos_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: cosmos-left
    
  - board: nice_nano_v2
    shield: cosmos_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: cosmos-right
    
  - board: seeeduino_xiao_ble
    shield: cosmos_dongle dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000 -DCONFIG_ZMK_STUDIO=y
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: cosmos-dongle-screen

  # - board: seeeduino_xiao_ble
  #   shield: settings_reset
  #   artifact-name: reset-dongle-settings

  # - board: nice_nano_v2
  #   shield: settings_reset
  #   artifact-name: reset-splits-settings