include:
  - board: nice_nano_v2
    shield: cosmos_left
    
  - board: nice_nano_v2
    shield: cosmos_right
    
  - board: seeeduino_xiao_ble 
    shield: cosmos_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: zmk-usb-logging

  - board: seeeduino_xiao_ble
    shield: settings_reset

  - board: nice_nano_v2
    shield: settings_reset