include:
  - board: nice_nano
    shield: cosmos_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: cosmos-left
    
  - board: nice_nano
    shield: cosmos_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    # snippet: zmk-usb-logging
    artifact-name: cosmos-right
    
  - board: seeeduino_xiao_ble
    shield: cosmos_dongle dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    # snippet: zmk-usb-logging
    artifact-name: cosmos-dongle-screen

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: cosmos-dongle-settings-reset

  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: cosmos-splits-settings-reset